import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Web3Provider from "@/contexts/Web3Provider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Account } from "@/components/Account";
import { WalletOptions } from "@/components/WalletOptions";
import { useAccount } from "wagmi";
import ConnectButton from "@/components/ConnectButton";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { NavigationMenu } from "@/components/ui/navigation-menu";
import Navbar from "@/components/Navbar";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Web3Provider>
          <div className="min-h-screen bg-gray-900 text-white">
            <Navbar />
            <main className="container mx-auto p-8">{children}</main>
          </div>
        </Web3Provider>
      </body>
    </html>
  );
}
